# Generated by Django 3.1 on 2020-08-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
