# Generated by Django 3.1 on 2020-08-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_from',
            field=models.DateTimeField(default='2020-08-24 16:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='date_to',
            field=models.DateTimeField(null=True),
        ),
    ]
