# Generated by Django 3.1 on 2020-08-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_auto_20200825_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_all_day',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_important',
            field=models.BooleanField(default=False, verbose_name='Important'),
        ),
    ]
