# Generated by Django 3.1 on 2020-08-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='medias',
            field=models.ManyToManyField(to='gallery.Media'),
        ),
    ]
