# Generated by Django 3.1 on 2020-08-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallery_medias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='medias',
            field=models.ManyToManyField(null=True, to='gallery.Media'),
        ),
    ]
