# Generated by Django 3.1 on 2020-08-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20200820_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='medias',
        ),
        migrations.AddField(
            model_name='media',
            name='galleries',
            field=models.ManyToManyField(to='gallery.Gallery'),
        ),
    ]
