# Generated by Django 3.1 on 2020-08-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20200820_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='cover',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
