# Generated by Django 3.1 on 2020-08-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20200821_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='cover',
            field=models.ImageField(null=True, upload_to='user_images/'),
        ),
    ]
