# Generated by Django 3.1 on 2020-08-21 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0009_auto_20200821_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='galleries',
            field=models.ManyToManyField(null=True, to='gallery.Gallery'),
        ),
        migrations.AlterField(
            model_name='media',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
