# Generated by Django 3.1 on 2020-08-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_auto_20200821_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
