# Generated by Django 3.1 on 2020-08-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_gallery_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='galleries',
            field=models.ManyToManyField(to='gallery.Gallery'),
        ),
    ]
