# Generated by Django 3.1 on 2020-08-25 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='invitations',
            field=models.ManyToManyField(related_name='invited_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
