# Generated by Django 3.1 on 2020-08-25 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('family', '0002_family_invitations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='invitations',
        ),
        migrations.AddField(
            model_name='family',
            name='invited_users',
            field=models.ManyToManyField(related_name='inviting_families', to=settings.AUTH_USER_MODEL),
        ),
    ]
