# Generated by Django 3.1 on 2020-08-25 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('family', '0004_family_requesting_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='invited_users',
            field=models.ManyToManyField(blank=True, related_name='inviting_families', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='family',
            name='requesting_users',
            field=models.ManyToManyField(blank=True, related_name='requested_families', to=settings.AUTH_USER_MODEL),
        ),
    ]
